{
    'name': 'Time Off - Attendance',
    'version': '16.0.1',
    'summary': 'Related Time Off to Attendance',
    'author': 'github.com/zdni',
    'license': 'LGPL-3',
    'category': 'Human Resources',
    'depends': [
        'approvals',
        'approvals_evidence',
        'approvals_portal',
        'approvals_position',
        'approvals_refused_reason',
        'approvals_settings',
        'custom_payroll',
        'employee_attendance',
        'hr_attendance',
        'hr_employee_service',
        'hr_holidays',
        'hr_payroll',
        'hr_payroll_holidays',
        'hr_work_entry_holidays',
        'project',
        'project_timesheet_holidays',
    ],
    'data': [
        'data/approval_category_data.xml',
        'data/hr_leave_type_data.xml',
        'data/hr_salary_rule_data.xml',
        'data/scheduled_action.xml',

        'views/hr_leave_type.xml',
        'views/hr_payslip_views.xml',
        'views/res_config_settings_views.xml',
    ],
    'auto_install': False,
    'application': False,
}