{
    'name': 'Base Setting for PT. Kokai Indo Abadi',
    'version': '16.0',
    'summary': 'Base Menu and Module for PT. Kokai Indo Abadi',
    'author': 'github.com/zdni',
    'license': 'LGPL-3',
    'category': 'Base',
    'depends': [
        'access_apps',
        'access_restricted',
        'access_settings_menu',
        'account',
        'account_financial_report',
        'accounting_pdf_reports',
        'approvals',
        'auditlog',
        'auto_backup',
        'base',
        'calendar',
        'contacts',
        'crm',
        'date_range',
        'data_recycle',
        'documents',
        'fleet',
        'helpdesk',
        'hr',
        'hr_attendance',
        'hr_contract',
        'hr_holidays',
        'hr_timesheet',
        'hr_recruitment',
        'ir_rule_protected',
        'knowledge',
        'ks_dashboard_ninja',
        'ks_dn_advance',
        'maintenance',
        'mrp',
        'odoo_num2words',
        'odoo_python_pip_install_library',
        'om_account_accountant',
        'opsway_2many_clickable_tag',
        'payroll',
        'product',
        'product_variant_configurator',
        'project',
        'ps_binary_field_attachment_preview',
        'purchase',
        'purchase_request',
        'query_deluxe',
        'report_py3o',
        'report_xlsx',
        'res_localization',
        'rowno_in_tree',
        'sale_management',
        'sequence_reset_period',
        'stock',
        'survey',
        'timesheet_grid',
        'web_debranding',
    ],
    'data': [
        'views/base_menu_views.xml',
        'security/group_security.xml',
    ],
    'auto_install': False,
    'application': False,
}