{
    'name': 'Employee Overtime',
    'version': '16.0',
    'summary': 'Employee Overtime Request Form',
    'author': 'github.com/zdni',
    'license': 'LGPL-3',
    'category': 'Human Resources',
    'depends': [
        'approvals',
        'approvals_evidence',
        'approvals_portal',
        'approvals_position',
        'approvals_refused_reason',
        'approvals_settings',
        'custom_activity',
        'custom_payroll',
        'hr',
        'hr_attendance',
        'hr_payroll',
        'sequence_reset_period',
    ],
    'data': [
        'data/approval_category_data.xml',
        'data/hr_allowance_data.xml',
        'data/hr_salary_rule_data.xml',
        'data/overtime_type_data.xml',
        'data/ir_sequence.xml',

        'security/group_security.xml',
        'security/ir_rules.xml',
        'security/ir.model.access.csv',

        'views/hr_overtime_views.xml',
        'views/hr_payslip_views.xml',
        'views/res_config_settings_views.xml',
    ],
    'auto_install': False,
    'application': False,
}