{
    'name': 'CRM Management',
    'version': '16.0',
    'summary': 'This module for add CRM Management that complies with PT. Kokai Indo Abadi rules',
    'author': 'github.com/zdni',
    'license': 'LGPL-3',
    'category': 'Sales',
    'depends': [
        'approvals_evidence', 
        'approvals_settings',
        'confirmation_wizard',
        'crm', 
        'crm_iap_enrich',
        'custom_activity',
        'department_detail',
        'many2many_attachment_preview',
        'minutes_of_meeting',
        'report_py3o',
        'sale_crm',
        'sale_product_configurator',
        'sequence_reset_period',
    ],
    'data': [
        'data/account_analytic_plan_data.xml',
        'data/approval_category_data.xml',
        'data/product_category_data.xml',
        'data/data.xml',
        'data/ir_sequence_data.xml',
        'data/order_term_list_data.xml',
        
        'security/group_security.xml',
        'security/ir.model.access.csv',

        'views/menu.xml',
        'views/approval_request_views.xml',
        'views/contract_issue_views.xml',
        'views/crm_lead_views.xml',
        'views/hr_department_views.xml',
        'views/sale_order_views.xml',
        'views/stage_history_views.xml',
        'views/tracking_requirement_values_template.xml',
        'views/res_config_settings_views.xml',

        'wizards/stage_change_wizard.xml',
        'wizards/stage_lost_wizard_views.xml',
        'wizards/generate_product_wizard_views.xml',
    ],
    'auto_install': False,
    'application': False,
}