{
    'name': 'Employee Attendance',
    'version': '16.0',
    'description': '',
    'summary': 'Employee Attendance Data',
    'author': 'github.com/zdni',
    'website': '',
    'license': 'LGPL-3',
    'category': 'Human Resources',
    'depends': [
        'hr', 
        'hr_contract',
        'hr_attendance', 
        'hr_payroll',
        'hr_work_entry', 
        'kokai_hr_work_entry_contract_attendance',
        'resource',
        'approvals',
        'approvals_evidence',
        'approvals_portal',
        'approvals_position',
        'approvals_refused_reason',
        'approvals_settings',
    ],
    'data': [
        'data/approval_category_data.xml',
        'data/hr_work_entry_type_data.xml',
        'data/ir_sequence.xml',

        'security/group_security.xml',
        'security/ir_rules.xml',
        'security/ir.model.access.csv',

        'views/employee_shift_views.xml',
        'views/hr_attendance_views.xml',
        'views/res_config_settings_views.xml',
        'views/resource_views.xml',

        'wizards/employee_shift_replaced_wizard_views.xml',
        'wizards/generate_complete_attendance_wizard_views.xml',
    ],
    'auto_install': False,
    'application': False,
}